addons:
  sauce_connect: true
env:
  global:
    - secure: EgqnS9rTmIGzu8FL2pJcyf34akKQWd2LJaAIaRb0TjEsHxiEbVGhJlwg9Tg6qRK3dyiLIbwJoj16IulZV343euwCmHUtQPkVArrv2p1uikoG6lLe0N2fgkDGT61FLV9tFWRLjvMO6xBZJ9doBt+/wUZLfA2zM6G6JHxaLfGHio8=
    - secure: TOVAOWF2dsYY+dpBukq/UCkStU/zYuuf0+As/6/gv1gK1n+azCUP1o6czOdGj2mTe6A4Jg9B5gzPconrgyuC78FBPxaZCR594RqGlLDZT77VrwM2i6HuQP2+YXXBNGQkl7baVxGiL0+i39fRH7QsxMX5pm4R/bFMLM1IhAoUiGY=
language: node_js
node_js:
    - "0.12"
sudo: false
